<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { FileText, History, ClipboardCheck, Upload, Play, RotateCcw, Send, Trash2, ArrowLeft, ShieldCheck } from 'lucide-vue-next'

type Issue = { id:string; type:string; severity:string; quote:string; location:string; explanation:string; missingConditions:string[]; questions:string[]; acceptanceCriteria:string[]; relatedRoles:string[]; reworkRisk:string }
type Report = { summary:string; riskLevel:string; counts:{high:number;medium:number;low:number}; issues:Issue[] }
type Review = { id:string; text:string; mode:string; createdAt:string; report:Report; versions:Report[] }
type HistoryItem = { id:string; createdAt:string; summary:string; riskLevel:string; counts:{high:number;medium:number;low:number} }
const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api'
const page = ref<'review'|'result'|'history'>('review'); const text=ref(''); const mode=ref('全面审查'); const loading=ref(false); const uploading=ref(false); const error=ref(''); const fileName=ref(''); const current=ref<Review|null>(null); const history=ref<HistoryItem[]>([]); const filter=ref('all'); const question=ref('')
const typeNames:Record<string,string>={ambiguous_term:'模糊表达',missing_boundary:'缺少边界条件',conflict:'相互矛盾',permission:'角色或权限',testability:'不可测试',security:'安全风险',operational:'运营异常'}
const visibleIssues=computed(()=>current.value?.report.issues.filter(i=>filter.value==='all'||i.type===filter.value)||[])
async function request(path:string, options:RequestInit={}){ const res=await fetch(API+path,options); const data=await res.json().catch(()=>({error:'服务器返回无效内容'})); if(!res.ok) throw new Error(data.error||'请求失败'); return data }
async function upload(file:any){ uploading.value=true; error.value=''; try { const form=new FormData(); form.append('file',file.raw); const data=await request('/reviews/upload',{method:'POST',body:form}); text.value=data.text; fileName.value=data.fileName; ElMessage.success(`已解析 ${data.characters} 个字符`) } catch(e:any){ error.value=e.message } finally{uploading.value=false} }
async function review(){ if(!text.value.trim()){error.value='请先输入或上传需求文本';return} loading.value=true;error.value='';try{current.value=await request('/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.value,mode:mode.value})});page.value='result'}catch(e:any){error.value=e.message}finally{loading.value=false} }
async function follow(){if(!question.value.trim()||!current.value)return;loading.value=true;try{current.value=await request(`/reviews/${current.value.id}/follow-up`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:question.value})});question.value='';ElMessage.success('已生成新版本')}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function loadHistory(){try{history.value=await request('/reviews')}catch(e:any){error.value=e.message}}
async function openHistory(id:string){loading.value=true;try{current.value=await request(`/reviews/${id}`);page.value='result'}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function remove(id:string){await ElMessageBox.confirm('删除后不可恢复，确认删除？','删除记录',{type:'warning'});try{await request(`/reviews/${id}`,{method:'DELETE'});await loadHistory();ElMessage.success('已删除')}catch(e:any){error.value=e.message}}
function reset(){text.value='';fileName.value='';current.value=null;error.value='';page.value='review'}
function editAgain(){if(current.value){text.value=current.value.text;page.value='review'}}
onMounted(loadHistory)
</script>
<template><div class="app-shell"><header class="topbar"><div class="brand"><div class="brand-mark"><ShieldCheck :size="20"/></div><div><strong>需求歧义审查器</strong><span>把不确定性变成可验证的任务</span></div></div><nav><button :class="{active:page==='review'||page==='result'}" @click="page=current?'result':'review'"><ClipboardCheck :size="16"/>审查</button><button :class="{active:page==='history'}" @click="page='history';loadHistory()"><History :size="16"/>历史记录</button></nav></header><main>
<section v-if="page==='review'" class="workspace"><div class="page-heading"><div><p class="eyebrow">REQUIREMENT REVIEW</p><h1>先把需求说清楚，再开始开发</h1><p class="muted">粘贴课程作业需求，或上传 Word / 文字型 PDF，系统会标出模糊点、边界缺口和验收风险。</p></div><div class="step">01 <span>输入需求</span></div></div><div class="input-layout"><section class="panel input-panel"><div class="panel-title"><div><h2>需求内容</h2><p>原文会被引用到审查报告中</p></div><el-button text @click="reset"><RotateCcw :size="15"/>清空</el-button></div><el-input v-model="text" type="textarea" :rows="16" maxlength="20000" show-word-limit placeholder="例如：用户可以尽快完成注册，并方便地查看自己的订单……"/><div class="file-row"><el-upload :auto-upload="false" :show-file-list="false" accept=".docx,.pdf" :on-change="upload"><el-button :loading="uploading"><Upload :size="16"/>上传 Word / PDF</el-button></el-upload><span v-if="fileName" class="file-name"><FileText :size="15"/> {{fileName}}</span><span v-else class="muted">支持 .docx、文字型 .pdf，单文件不超过 10MB</span></div></section><aside class="panel options"><h2>审查设置</h2><p>Mock 模式无需配置 API Key，也可以完整演示。</p><label>审查模式</label><el-select v-model="mode"><el-option label="全面审查" value="全面审查"/><el-option label="重点关注可测试性" value="可测试性"/><el-option label="重点关注安全与权限" value="安全与权限"/></el-select><div class="check-list"><div><span class="dot green"></span><span>原文引用</span><b>已启用</b></div><div><span class="dot amber"></span><span>AI 分析</span><b>Mock / 千问</b></div><div><span class="dot blue"></span><span>历史保存</span><b>H2 数据库</b></div></div><el-button type="primary" size="large" class="start" :loading="loading" @click="review"><Play :size="17"/>开始审查</el-button></aside></div></section>
<section v-else-if="page==='result'&&current" class="workspace"><div class="result-head"><div><button class="back" @click="page='review'"><ArrowLeft :size="16"/>编辑需求</button><p class="eyebrow">REVIEW REPORT</p><h1>审查结果</h1><p class="muted">{{new Date(current.createdAt).toLocaleString('zh-CN')}} · {{current.mode}}</p></div><el-button type="primary" plain @click="editAgain">修改后重新审查</el-button></div><div class="summary panel"><div><span class="risk-pill" :class="current.report.riskLevel">{{current.report.riskLevel==='high'?'高风险':current.report.riskLevel==='medium'?'中风险':'低风险'}}</span><h2>{{current.report.summary}}</h2></div><div class="counts"><div><b class="high">{{current.report.counts.high}}</b><span>高风险</span></div><div><b class="medium">{{current.report.counts.medium}}</b><span>中风险</span></div><div><b class="low">{{current.report.counts.low}}</b><span>低风险</span></div></div></div><div class="filterbar"><span>问题清单</span><el-radio-group v-model="filter" size="small"><el-radio-button label="all">全部 {{current.report.issues.length}}</el-radio-button><el-radio-button v-for="(name,key) in typeNames" :key="key" :label="key">{{name}}</el-radio-button></el-radio-group></div><div v-if="!visibleIssues.length" class="empty panel"><ClipboardCheck :size="38"/><h3>这个筛选下暂无问题</h3><p>可以切换筛选条件查看完整报告。</p></div><article v-for="issue in visibleIssues" :key="issue.id" class="issue panel"><div class="issue-head"><div><span class="type-label">{{typeNames[issue.type]||issue.type}}</span><h2>{{issue.explanation}}</h2></div><span class="severity" :class="issue.severity">{{issue.severity==='high'?'高':issue.severity==='medium'?'中':'低'}}</span></div><blockquote>“{{issue.quote}}” <small>{{issue.location}}</small></blockquote><div class="issue-grid"><div><h4>缺失条件</h4><ul><li v-for="x in issue.missingConditions" :key="x">{{x}}</li></ul></div><div><h4>需要确认</h4><ul><li v-for="x in issue.questions" :key="x">{{x}}</li></ul></div><div><h4>可测试验收标准</h4><ul><li v-for="x in issue.acceptanceCriteria" :key="x">{{x}}</li></ul></div><div><h4>相关角色 · 返工风险</h4><p class="roles">{{issue.relatedRoles.join(' · ')}}</p><p>{{issue.reworkRisk}}</p></div></div></article><div class="follow panel"><div><h2>继续追问</h2><p class="muted">针对这份报告询问优先级、处理建议或补充条件</p></div><div class="follow-input"><el-input v-model="question" placeholder="例如：先处理哪个问题？" @keyup.enter="follow"/><el-button type="primary" :loading="loading" @click="follow"><Send :size="16"/>发送</el-button></div></div></section>
<section v-else class="workspace"><div class="page-heading"><div><p class="eyebrow">REVIEW HISTORY</p><h1>历史审查</h1><p class="muted">每次重新审查都会保留，方便回看需求如何变得更清晰。</p></div><div class="step">03 <span>历史版本</span></div></div><div v-if="!history.length" class="empty panel"><History :size="42"/><h3>还没有审查记录</h3><p>完成第一次需求审查后，记录会显示在这里。</p><el-button type="primary" @click="page='review'">开始第一次审查</el-button></div><div v-else class="history-list"><article v-for="item in history" :key="item.id" class="history-item panel"><div class="history-icon"><FileText :size="20"/></div><div class="history-main"><h3>{{item.summary}}</h3><p>{{new Date(item.createdAt).toLocaleString('zh-CN')}}</p></div><div class="mini-counts"><span class="high">{{item.counts.high||0}} 高</span><span class="medium">{{item.counts.medium||0}} 中</span><span class="low">{{item.counts.low||0}} 低</span></div><el-button text @click="openHistory(item.id)">查看详情</el-button><el-button text type="danger" @click="remove(item.id)"><Trash2 :size="16"/></el-button></article></div></section><el-alert v-if="error" class="error" type="error" :closable="false" show-icon>{{error}}</el-alert></main></div></template>
